export const REGISTRAR_POKEMON = "REGISTRAR_POKEMON";
export const AGREGAR_POKEMON_LISTA = "AGREGAR_POKEMON_LISTA";
export const ERROR_POKEMON = "ERROR_POKEMON";
export const ELIMINAR_ERROR = "ELIMINAR_ERROR";
export const DESCARTAR_POKEMON = "DESCARTAR_POKEMON";
export const POKEMON_REPETIDO = "POKEMON_REPETIDO";